# Generated by Django 2.1.7 on 2019-03-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190321_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='username',
        ),
    ]
