# Generated by Django 2.1.7 on 2019-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='Alfredemmanuelinyang@gmail.com', max_length=254),
        ),
    ]
