# Generated by Django 2.1.7 on 2019-03-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190321_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='username',
            new_name='name',
        ),
    ]
