# Generated by Django 2.1.7 on 2019-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190326_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Example: Body of message', max_length=10000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Example: Subject of discussion', max_length=100),
        ),
    ]
